### PR TITLE
Trello ticket #9 View all Categories

### PR DESCRIPTION
**Pull request by KNR84**
### **Trello information:**
Ticket link: https://trello.com/c/7XFrtBcl/9-9-view-all-categories
Given an admin is in the app
When they select the Category Management link in the menu
Then they should be directed to a page that lists all the Category names ordered alphabetically

### **Description of changes:**
The Category Management link was added to the homepage and links to the newly created Category list. The Category page lists ALL Categories in alphabetical order, displaying the Category Id, Name and links to Edit, Delete and view Details of each Category. There is also a Create New category link at the top of the page. Functionality for the Edit, Delete, view Details and Create New link have NOT yet been added.

### **Files and Methods created:**
- ICategory repository was added to declare the Get All method to list the categories. 
- An order by clause was added to the SQL statement in the Category Repository to assure the list would populate in alphabetical order. 
- A Navbar menu option/link was added for Category Management page in Shared>_Layout.cshtml

### **Type of change:**
- [x] New feature (non-breaking change which adds functionality)

### **Testing Instructions:**
- Clone this project’s repository to your machine
- If you’ve already done this and are currently working on a different branch of the project, be sure to git add and git commit whatever you’re working on on your branch, before you attempt to switch branches
- Then git checkout main to switch to the project’s main branch
- Navigate to the root directory for this repo (yourParentFolderName/tabloidmvc-inferno-crusher)
- git fetch -a to retrieve the current remote-tracked branches for the project, you should see a branch named krViewCategory as one of the available branches
- git checkout krViewCategory to switch to my branch
- If you don't see the most recent version of my files, git pull origin krViewCategory
- Start TabloidMVC.sln to open the project in Visual Studio
- If you haven’t created the TabloidMVC database, please do so in Visual Studio and use the following SQL scripts to populate it accordingly:
- Start a new query in your database and copy in this SQL script before running to fill out tables and columns: [First SQL Script for Creating DB](https://github.com/NewForce-Cohort-8/tabloidmvc-inferno-crusher/blob/main/SQL/01_TabloidMVC_Create_DB.sql)
- ctrl + a and delete what is in that query and replace it with this SQL script before running to seed the database: [Second SQL Script for Seeding DB](https://github.com/NewForce-Cohort-8/tabloidmvc-inferno-crusher/blob/main/SQL/02_TabloidMVC_Seed_Data.sql)
- Click the execute with debugger solid green button to launch the app
- In your browser, please go to Login on the nav bar and log in with this email: admin@example.com - this should redirect you back to the home page.
- At the homepage click on the CATEGORY MANAGEMENT link in the nav bar. 
- You should see a Category List on this screen. 
- The page begins with a Create New category link (this button does not yet function)
- Under the link you will see a populated list including an id column, name column and three link buttons Edit, Details and Delete. These links also do not function. 
- The list should display in alphabetical order. 
- Verify that each field is populated with its corresponding value from the database. If you need to verify, you may run a query: SELECT id, name FROM Category ORDER BY name

### **Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by sarahebrooks12** [comment]
- Please include a SQL query that the tester can use to make sure that the browser is displaying the correct information - see Darrin or Colin's for an example

**Review by CeeFM — APPROVED** [review]
This works as you described in the thorough test instructions! Once Sarah approves the amount of cowbell and another teammate approves, then this should be good to go in my book!

**Review by darrindoc — APPROVED** [review]
@KNR84 

Everything works as expected per your instructions

**Review by sarahebrooks12 — APPROVED** [review]
Looks great!

**Pull request merged**
