### PR TITLE
Ticket 8 - Edit A Post

### PR DESCRIPTION
**Pull request by darrindoc**
**Description**

This update allows a user to UPDATE one of their currently existing post from the main Post list. An "Edit" button for posts originally existed in the post list and in the "Post Details" section, but was previously nonfunctional. A user show now be able to use this button which will 

1. Open a form similar to what is presented when a post is originally created
2. Populate the form with data currently existing for this post in the "Post" table of the Database to corresponding inputs
3. Allow the user to modify the content of any of these presented fields
4. Save the changes and overwrite the "Post" table for any field that was changed, while leaving unchanged fields as they were.

**Created/Updated the following files and methods:**

- Created Model under ViewModels>PostEditViewModel.cs 
- Updated PostRepository.cs  to create Edit Action
- Updated PostController.cs to add GET request for Edit Action and to run POST for Edit
- Created Edit.cshtml for update form
- Created PostDetailsViewModel in Models>ViewModels>PostDetailsViewModel.cs
- Updated NewPostFromReader method in Repositories>PostRepository.cs to include IsApproved field

**Related Ticket(s)**
https://trello.com/c/yXB7eViX/8-8-edit-a-post

Ticket #8- Edit A Post

**Type of Change**

- [X] New feature (non-breaking change which adds functionality)

**Testing Instructions**

- Clone this project’s repository to your machine
  -If you’ve already done this and are currently working on a different branch of the project, be sure to `git add` and `git commit` whatever you’re working on on your branch, before you attempt to switch branches
  -Then `git checkout main` to switch to the project’s main branch)
- Navigate to the root directory for this repo (yourParentFolderName/tabloidmvc-inferno-crusher)
- `git fetch -a` to retrieve the current remote-tracked branches for the project, you should see a branch named `dd-edit-post` as one of the available branches
- `dd-edit-post` to switch to my branch
- If you don't see the most recent version of my files, `git pull origin dd-edit-post`
- `Start TabloidMVC.sln` to open the project in Visual Studio
- If you haven’t created the TabloidMVC database, please do so in Visual Studio and use the following SQL scripts to populate it accordingly:
  - Start a new query in your database and copy in this SQL script before running to fill out tables and columns: [First SQL Script for Creating DB](https://github.com/NewForce-Cohort-8/tabloidmvc-inferno-crusher/blob/main/SQL/01_TabloidMVC_Create_DB.sql)
  - ctrl + a and delete what is in that query and replace it with this SQL script before running to seed the database: [Second SQL Script for Seeding DB](https://github.com/NewForce-Cohort-8/tabloidmvc-inferno-crusher/blob/main/SQL/02_TabloidMVC_Seed_Data.sql)
- Click the execute with debugger solid green button to launch the app
- In your browser, please go to `Login` on the nav bar and log in with this email: `admin@example.com` - this should redirect you back to the home page. If already logged in, you may skip this step.
- Click the “POSTS” link/option on the nav bar to get to the Posts page
- Click the View/eyeball Icon next to any post where the "Author" is the user currently logged in. This will redirect you to that post’s individual details page (/Post/Details/1).
- Click the button with the "pencil" symbol.
- A form will appear with the phrase "What do you have to say?" at the top. Input fields are labeled with their corresponding field in the database
- Verify that each field is already populated with its corresponding value from the database. If you need to verify, you may run a query: 
                SELECT * FROM Post WHERE Id = <insert the Id of your post here>

- Edit fields using the form by either typing, selecting a date or utilizing the dropdown menu, depending on the field's presentation in the form.
- Click the “SAVE" button.
- You will be routed back to this post's "Post Details" screen.
- Verify that the specific changes you made inside the form have taken effect in their corresponding fields.
- If the "Edit" button inside "Post Details" is working as expected, we will not test the "Edit" button inside the Post List. Click the "POSTS" tab in the NavBar to navigate back to the full list of posts.
- Locate a post where the "Author" is the user currently logged in. Click the "Edit" button (signified by a pencil). This should be located between the "View" and "Delete" buttons.
- You should be presented with the same Edit form that was tested before.
- A form will appear with the phrase "What do you have to say?" at the top. Input fields are labeled with their corresponding field in the database
- Verify that each field is already populated with its corresponding value from the database. If you need to verify, you may run a query: 
                SELECT * FROM Post WHERE Id = <insert the Id of your post here>

- Edit fields using the form by either typing, selecting a date or utilizing the dropdown menu, depending on the field's presentation in the form.
- Click the “SAVE" button.
- You will be routed back to this post's "Post Details" screen.
- Verify that the specific changes you made inside the form have taken effect in their corresponding fields.
- Testing is considered successful if the "Edit" button functions as above both in the post's "Post Details" section and when accessed for a specific post via the Post List

Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] My changes generate no new warnings or errors
- [X] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by CeeFM — APPROVED** [review]
Edit works as you have outlined in your thorough testing instructions! Bravo!

**Review by sarahebrooks12 — APPROVED** [review]
This is just about perfect - make sure to include where they can get the post id from (the route) in the SQL queries 👼🏻

**Comment by KNR84** [comment]
This feature works as expected. -KR

YAY!

**Review by KNR84 — COMMENTED** [review]
Code works as expected -KR

**Pull request merged**
